LEARNING_RATE: 0.02
BETA_1: 0.99
EPSILON: 1e-1
TOTAL_VARIATION_WEIGHT: 30
EPOCHS: 10
STEPS_PER_EPOCH: 100
STYLE_WEIGHT: 1e-2
CONTENT_WEIGHT: 1e4
MAX_DIM: 512
STYLE_LAYERS:
  - block1_conv1
  - block2_conv1
  - block3_conv1
  - block4_conv1
  - block5_conv1
CONTENT_LAYERS:
  - block5_conv2
SAVE_KERAS: false
